
export const types = {
    CLEAR_POSTS:       'CLEAR_POSTS',
    CREATE_POST:       'CREATE_POST',
    CREATE_POST_ASYNC: 'CREATE_POST_ASYNC',
    FETCH_POSTS_ASYNC: 'FETCH_POSTS_ASYNC',
    FILL_POSTS:        'FILL_POSTS',
    LIKE_POST: 'LIKE_POST',
    LIKE_POST_ASYNC: 'LIKE_POST_ASYNC',
    REMOVE_POST: 'REMOVE_POST',
    REMOVE_POST_ASYNC: 'REMOVE_POST_ASYNC',
    UNLIKE_POST: 'UNLIKE_POST',
    UNLIKE_POST_ASYNC: 'UNLIKE_POST_ASYNC',
};
