
export const types = {
    EMIT_ERROR: 'EMIT_ERROR',
    SET_OFFLINE_STATE: 'SET_OFFLINE_STATE',
    SET_ONLINE_STATE: 'SET_ONLINE_STATE',
    START_FETCHING: 'START_FETCHING',
    STOP_FETCHING: 'STOP_FETCHING',
};
